### ISSUE TITLE
decompress contents in preview

### ISSUE THREAD

**Issue by holic** [holic/ethfs#17]
from @xtremetom 
> On the display, it might be good to decode it so users can verify the code
> ![image](https://user-images.githubusercontent.com/508855/211422769-483dc70e-2e75-4b39-bc63-daff73bd9e0d.png)

probably wanna do this in a way that avoids zip bombs

**Comment by xtremetom** [comment]
Good note on the zip bombs :)

**Comment by holic** [comment]
Done in  https://github.com/holic/ethfs/commit/a22539fccf9a4e3d6e53c10e78b4a33d02697820
